### ISSUE TITLE
C# egységtesztekről egy rövid áttekintés

### ISSUE THREAD

**Issue by piller-imre** [danielstreba/szakdolgozat#1]
Nem kell túl általánosan belemenni. Azt kellene csak röviden bemutatni, hogy C#-ban egyáltalán milyen formában érhetők el a tesztek.

**Comment by danielstreba** [comment]
Az egységtesztelés a szoftvertesztelés egy olyan módszere, amely során a forráskód legalacsonyabb szintű, a programot felépítő egységeket tesztelik. Az egység egy rendszer legkisebb önálló egységként tesztelhető része. Az egységtesztekkel ellenőrizhető, hogy egy egység az elvárásoknak megfelelően működik. Egy egység függvényeiről ellenőrizzük, hogy különböző bemenetek esetén megfelelő eredményt, vagy hibát produkálnak. Az egységeket egymástól függetlenítve kell tesztelni.

Az egységtesztelés nem egy új fogalom a szoftverfejlesztésben, az 1970-es évektől, a Smalltalk programozási nyelv korai napjai óta jelen van, és ez az egyik legjobb módszer arra, hogy a fejlesztő növelje a kód minőségét miközben jobban megérti az adott osztály vagy metódus működését. Kent Beck vezette be az egységtesztelés koncepcióját a Smalltalk-ban, és ez a fogalom átöröklődött sok más nyelvbe is, ezzel az egységtesztelést egy rendkívül hasznos gyakorlattá téve.

A C# programozási nyelvben és a .NET keretrendszerben nincs gyári, beépített egységtesztelő keretrendszer, így mind a tesztek írásához, futtatásához és az eredmények megjelenítéséhez szükség van egy ezt támogató keretrendszerre.

Napjainkban a legnépszerűbb egységteszt keretrendszerek a következők:
- MSTest
- xUnit.NET
- NUnit

Az egységtesztek felépítése mind három, előzőleg említett keretrendszerben hasonló. Miután Kent Beck a Smalltalk-ban bevezette az egységtesztelést és megírta az SUnit keretrendszert, más fejlesztők adaptálták a SUnit-ot más programozási nyelvekre és megtartották a Kent Beck által bevezetett ötleteket. Az SUnit-ot alapul vevő egységtesztelő keretrendszereket nevezzük összefoglaló néven xUnit keretrendszereknek.

Mindhárom keretrendszer ingyenes, és nyílt forráskódú. Az MSTest keretrendszert habár a Microsoft fejleszti szintén mint a C# nyelvet és a .NET környezetet, de ez nincs alapértelmezetten a C#-ba vagy a .NET környezetbe integrálva. Az xUnit.NET-et a Microsoft hivatalosan is használja több szoftverének tesztelésében is, például az ASP.NET Core forráskódhoz ezzel a keretrendszerrel készítik az egységteszteket.

A szakdolgozatban a xUnit.NET keretrendszer kerül felhasználásra.

Ezeket a keretrendszereket többféleképpen is elérhetjük a programunkban. Manapság a legnépszerűbb a NuGet csomagkezelő rendszer használata, ez a rendszer nagyon hasonló, funkciójában szinte megegyező a Linux-os apt csomagkezelő rendszerhez. A NuGet-tel egyszerűen kereshetünk, letölthetünk a programunkhoz függvénykönyvtárakat amit rögtön telepíteni is tudunk. A NuGet megvizsgálja a programunk architekturáját illetve a használt .NET keretrendszert és annak verzióját majd az alapján letölti nekünk a megfelelő DLL fájlokat és hozzáadja a projekthez a DLL fájlhoz tartozó referenciát. A DLL fájlokat mi manuálisan is beszerezhetjük, vagy akár mi is lefordíthatjuk magunknak ha arra lenne szükség.

Miután telepítettük az általunk választott keretrendszert elkezdhetünk írni egységteszteket a kódunkhoz. Minden egységteszt metódus egy teszteset amiben egy másik adott kódot tesztelünk. Minden keretrendszernél kicsit másképpen néz ki a tesztek felépítése, de bevett szokás az, hogy az teszteseteket meg kell jelölnünk egy annotációval, azaz a metódust annotálnunk kell. xUnit.NET esetén a metódus felé a `[Fact]` vagy `[Theory]` kulcsszót kell illesztenünk, ezzel jelezzük a keretrendszerünknek, hogy ez egy teszteset.
Mivel nagyobb kódbázis esetén átláthatatlan lenne ha minden tesztesetet a tesztelendő osztályba raknánk bele ezért más keretrendszereknél elvárt az, hogy az egységteszteink számára új osztályt hozzunk létre, azaz már a meglévő osztályainkba nem tudunk teszteseteket létrehozni. Bevett szokás az, hogy új projektet hozunk létre ahol csak a tesztek osztályait és azok segítő osztályait tároljuk, de az is elegendő ha a meglévő projektben hozzuk létre az egységteszt osztályainkat. Az osztály létrehozása után, metódusonként írhatjuk meg a teszteseteinket. Az xUnit.NET-nél erre nincs szükség, azonban javasolt, hogy elkülönítve és jól megnevezve tároljuk a teszteseteket tartalmazó osztályokat és magukat a metódusokat.

Minden keretrendszerben elérhető egy `Assert` osztály, amivel állításokat, kritériumokat lehetünk a tesztjeinkbe. Ellenőrizhetjük, hogy például a metódusunk visszatérési értéke azaz az tényleges (actual) érték megegyezik-e a várt (expected) értékkel. Ezenkívül számos más kijelentést tehetünk. Például, hogy a tényleg érték tartalmaz-e valamit, üres-e, a várt típusú-e vagy, hogy éppen dob-e kivételt vagy sem. A teszteset akkor kerül teljesített (pass) állapotba, ha minden kritériumunknak megfelelt, és közben nem dobódott valamilyen el nem kapott kivétel. Ha ezeket nem teljesíti a tesztesetünk akkor bukott (fail) állapotba kerül.

**Comment by danielstreba** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write 'C# egységtesztekről egy rövid áttekintés'](https://trello.com/c/fQdmJAsl/7-write-c-egys%C3%A9gtesztekr%C5%91l-egy-r%C3%B6vid-%C3%A1ttekint%C3%A9s)
